-- Create database
CREATE DATABASE movie_db;

-- Creation
-- Users
CREATE TABLE "user" (
  id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username  VARCHAR(80)  NOT NULL UNIQUE,
  password  VARCHAR(200) NOT NULL
);

-- Movies
CREATE TABLE movie (
  id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(120) NOT NULL,
  date  VARCHAR(50)  NOT NULL
);

-- Reservations
CREATE TABLE reservation (
  id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id  INTEGER NOT NULL,
  movie_id INTEGER NOT NULL,
  CONSTRAINT reservation_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES "user"(id),
  CONSTRAINT reservation_movie_id_fkey
    FOREIGN KEY (movie_id) REFERENCES movie(id)
);

-- (Optional but recommended) indexes on the FK columns for join speed:
CREATE INDEX idx_reservation_user_id  ON reservation (user_id);
CREATE INDEX idx_reservation_movie_id ON reservation (movie_id);

-- Sample Insertion
INSERT INTO movie (title, "date") VALUES
  ('Inception',   '2025-10-09'),
  ('Interstellar','2025-10-10'),
  ('Tenet',       '2025-10-11');


-- Helper functionalities inside psql
-- Connect to DB
-- \c <db_name>
-- List tables inside the DB
-- \dt
-- Read
-- Select * From <table_name>;
-- Delete
-- Delete From <table_name> where <condition>;